version: '3.1'

services:

  pgdb:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - 5444:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080