spring:
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5444/jpa_demo?currentSchema=public
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

server:
  port: 6000
